### ISSUE TITLE
Make it possible to set the Girder URL via an environment variable

### ISSUE THREAD

**Issue by jwodder** [dandi/dandiarchive#468]
In order to facilitate running the Docker Compose setup with an alternative set of ports, it would be nice if the external port for the Girder container could be passed to the Dandiarchive/"client" container by doing something like:

```yaml
client:
    image: dandiarchive/dandiarchive-client
    depends_on:
      - girder
    ports:
      - "8086:80"
    environment:
      VUE_APP_API_ROOT: http://localhost:8081/api/v1
```

I've tried the above, and it doesn't work; whenever the external port for the Girder container is set to something other than 8080, accessing the client container just returns a blank page, regardless of whether the `environment` setting above is there or not.
